apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  root-password: cm9vdA==
  db-user: cm9vdA==
  db-password: cm9vdA==
  jwt-secret: c3VwZXItc2VjdXJlLWp3dC1zZWNyZXQta2V5
  db-host: bXlzcWw=
  db-name: bGVhdmVfZGI=
