{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "leave-management-system.fullname" . }}-frontend
  labels:
    {{- include "leave-management-system.labels" . | nindent 4 }}
    component: frontend
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "leave-management-system.selectorLabels" . | nindent 4 }}
    component: frontend
{{- end }}
