{{- if and .Values.mysql.enabled .Values.mysql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "leave-management-system.fullname" . }}-mysql-pvc
  labels:
    {{- include "leave-management-system.labels" . | nindent 4 }}
    component: mysql
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  {{- if .Values.mysql.persistence.storageClassName }}
  storageClassName: {{ .Values.mysql.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
{{- end }}
