{{- if and .Values.backend.enabled (not .Values.backend.secrets.externalSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "leave-management-system.fullname" . }}-secrets
  labels:
    {{- include "leave-management-system.labels" . | nindent 4 }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  root-password: {{ .Values.backend.secrets.inline.rootPassword | quote }}
  db-user: {{ .Values.backend.secrets.inline.dbUser | quote }}
  db-password: {{ .Values.backend.secrets.inline.dbPassword | quote }}
  jwt-secret: {{ .Values.backend.secrets.inline.jwtSecret | quote }}
  db-host: {{ .Values.backend.database.host | quote }}
  db-name: {{ .Values.backend.database.name | quote }}
{{- end }}
