{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "leave-management-system.serviceAccountName" . }}
  labels:
    {{- include "leave-management-system.labels" . | nindent 4 }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
