{{- if and .Values.serviceMonitor.enabled .Values.backend.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "leave-management-system.fullname" . }}-backend
  labels:
    {{- include "leave-management-system.labels" . | nindent 4 }}
    component: backend
    release: kube-prometheus
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      component: backend
  endpoints:
    - port: metrics-otel
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | default "10s" }}
{{- end }}
